"""OMR CV engine tests (Phase 2 — engine port).

Pure computer-vision tests: no database, no HTTP, no Cloudinary. They pin the
engine's behaviour against committed snapshots so that a future dependency bump
(OpenCV in particular) or an accidental threshold edit fails loudly rather than
silently shifting how sheets are read.

`expected_extractions.json` was generated by running this engine over the four
fixture sheets and verified to be byte-identical to the standalone
`OMR/omr_backend` implementation's output on the same images.
"""

import json
from pathlib import Path

import pytest

from app.modules.omr.engine.extractor import MIN_FILL
from app.modules.omr.engine.pipeline import OMRPipeline

FIXTURES = Path(__file__).parent / "fixtures" / "omr"
TEMPLATE = Path(__file__).parent.parent / "app" / "modules" / "omr" / "templates" / "plus_coaching_template.json"
SNAPSHOT = FIXTURES / "expected_extractions.json"

SCANNED_SHEETS = ["omr1", "omr2", "omr3"]


@pytest.fixture(scope="module")
def pipeline() -> OMRPipeline:
    return OMRPipeline(template_path=TEMPLATE, answer_key=None, debug=False)


@pytest.fixture(scope="module")
def expected() -> dict:
    return json.loads(SNAPSHOT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def results(pipeline: OMRPipeline) -> dict:
    """Process every fixture sheet once and share the results across tests."""
    return {
        name: pipeline.process(FIXTURES / f"{name}.jpg", student_id=name)
        for name in ["blank", *SCANNED_SHEETS]
    }


# --- Blank sheet: no false positives ------------------------------------------


def test_blank_sheet_yields_no_answered_questions(results: dict) -> None:
    answers = results["blank"]["answers"]
    assert len(answers) == 40
    assert [q for q, data in answers.items() if data["status"] != "blank"] == []


def test_blank_sheet_fill_scores_stay_below_threshold(results: dict) -> None:
    """Every bubble on an unmarked sheet must read well below MIN_FILL.

    This is the guard against false positives: the calibrated headroom is
    ~0.23 measured vs a 0.35 threshold. A dependency change that narrows that
    gap shows up here before it starts inventing answers on real sheets.
    """
    scores = [
        score
        for data in results["blank"]["answers"].values()
        for score in data["all_scores"].values()
    ]
    assert scores, "no bubble readings were produced for the blank sheet"
    assert max(scores) < MIN_FILL, f"blank sheet reached {max(scores):.4f}, threshold is {MIN_FILL}"


def test_blank_sheet_metadata_reads_as_unfilled(results: dict) -> None:
    metadata = results["blank"]["metadata"]
    assert metadata["class_value"]["value"] is None
    assert metadata["set_code"]["value"] is None
    assert metadata["roll_number"]["roll_number"] == "?" * 6
    assert metadata["subject_code"]["subject_code"] == "?" * 3


# --- Scanned sheets: stable extraction ----------------------------------------


@pytest.mark.parametrize("sheet", SCANNED_SHEETS)
def test_extraction_matches_snapshot(sheet: str, results: dict, expected: dict) -> None:
    result = results[sheet]
    snapshot = expected[sheet]

    assert result["success"] is True
    assert result["alignment_method"] == snapshot["alignment_method"]
    assert result["metadata"] == snapshot["metadata"]
    # Snapshot keys come back from JSON as strings; the engine keys by int.
    assert {str(q): data for q, data in result["answers"].items()} == snapshot["answers"]


@pytest.mark.parametrize("sheet", SCANNED_SHEETS)
def test_corner_marker_alignment_is_used(sheet: str, results: dict) -> None:
    """All fixture scans align on the registration squares — the preferred tier.

    A drop to "contour" or "resize" means marker detection regressed, which
    degrades accuracy long before it produces an outright failure.
    """
    assert results[sheet]["alignment_method"] == "markers"


def test_bytes_and_path_inputs_agree(pipeline: OMRPipeline) -> None:
    from_path = pipeline.process(FIXTURES / "omr1.jpg", student_id="omr1")
    from_bytes = pipeline.process((FIXTURES / "omr1.jpg").read_bytes(), student_id="omr1")

    assert from_bytes["metadata"] == from_path["metadata"]
    assert from_bytes["answers"] == from_path["answers"]
    assert from_bytes["alignment_method"] == from_path["alignment_method"]


def test_undersized_image_is_rejected(pipeline: OMRPipeline) -> None:
    import cv2
    import numpy as np

    tiny = np.zeros((100, 100, 3), dtype=np.uint8)
    payload = cv2.imencode(".png", tiny)[1].tobytes()

    result = pipeline.process(payload, student_id="tiny")
    assert result["success"] is False
    assert "too small" in result["message"].lower()


def test_undecodable_bytes_fail_cleanly(pipeline: OMRPipeline) -> None:
    result = pipeline.process(b"this is not an image", student_id="junk")
    assert result["success"] is False
    assert result["annotated_png"] is None


# --- Scoring ------------------------------------------------------------------


def test_scoring_against_the_sheet_s_own_answers_is_perfect(results: dict) -> None:
    """Feed omr1's own extracted answers back as the key — everything answered
    must score, and everything blank or multiple must not."""
    detected = results["omr1"]["answers"]
    answered = {str(q): d["answer"] for q, d in detected.items() if d["status"] == "answered"}

    scored = OMRPipeline(
        template_path=TEMPLATE, answer_key={"answers": answered}, debug=False
    ).process(FIXTURES / "omr1.jpg", student_id="omr1")["score"]

    assert scored["correct"] == len(answered)
    assert scored["wrong"] == 0
    assert scored["adjusted_score"] == float(len(answered))
    assert scored["percentage"] == 100.0


# --- Filesystem discipline ----------------------------------------------------


def test_processing_writes_nothing_to_disk(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The standalone engine wrote 12 JPEGs plus JSON per sheet into a debug
    directory resolved relative to the process cwd. Nothing may do that now:
    the deployment runs multiple uvicorn workers, so worker-local files are
    both unreachable and unbounded."""
    before = sorted(p.name for p in FIXTURES.iterdir())
    monkeypatch.chdir(tmp_path)

    pipe = OMRPipeline(template_path=TEMPLATE, answer_key=None, debug=False)
    result = pipe.process(FIXTURES / "omr1.jpg", student_id="omr1")

    assert result["success"] is True
    assert list(tmp_path.iterdir()) == [], "engine wrote files into the working directory"
    assert sorted(p.name for p in FIXTURES.iterdir()) == before


def test_debug_disabled_returns_no_overlay(results: dict) -> None:
    assert results["omr1"]["annotated_png"] is None


def test_debug_enabled_returns_png_bytes_in_memory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)

    pipe = OMRPipeline(template_path=TEMPLATE, answer_key=None, debug=True)
    result = pipe.process(FIXTURES / "omr1.jpg", student_id="omr1")

    overlay = result["annotated_png"]
    assert isinstance(overlay, bytes) and len(overlay) > 0
    assert overlay[:8] == b"\x89PNG\r\n\x1a\n", "overlay is not a PNG"
    assert list(tmp_path.iterdir()) == [], "debug rendering wrote files to disk"
