"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useMarkPayslipPaidMutation } from "@/hooks/use-payroll";
import { MONTH_LABELS, PAYROLL_STATUS_LABELS, PAYSLIP_STATUS_LABELS, type PayrollRunDetail } from "@/lib/api/payroll";

const RUN_STATUS_BADGE_VARIANT: Record<string, "success" | "warning" | "muted"> = {
  paid: "success",
  processed: "warning",
  draft: "muted",
};

const PAYSLIP_STATUS_BADGE_VARIANT: Record<string, "success" | "warning"> = {
  paid: "success",
  pending: "warning",
};

function formatMoney(amount: number): string {
  return amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function PayrollRunDetailView({ run, canManage = false }: { run: PayrollRunDetail; canManage?: boolean }) {
  const markPaidMutation = useMarkPayslipPaidMutation();

  return (
    <div className="flex flex-col gap-4">
      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <CardTitle>
              {MONTH_LABELS[run.period_month - 1]} {run.period_year}
            </CardTitle>
            <Badge variant={RUN_STATUS_BADGE_VARIANT[run.status] ?? "muted"}>{PAYROLL_STATUS_LABELS[run.status]}</Badge>
          </div>
          <CardDescription>
            Generated by {run.generated_by_name} &middot; {run.payslip_count} payslip
            {run.payslip_count === 1 ? "" : "s"} &middot; Total net {formatMoney(run.total_net_amount)}
          </CardDescription>
        </CardHeader>

        {run.skipped && run.skipped.length > 0 && (
          <div className="flex flex-col gap-1.5 px-4 pb-2">
            <span className="text-sm font-medium text-foreground">
              Skipped ({run.skipped.length}) — no salary structure effective for this period
            </span>
            <div className="flex flex-wrap gap-1.5">
              {run.skipped.map((employee) => (
                <Badge key={`${employee.employee_type}-${employee.teacher_id ?? employee.staff_id}`} variant="warning">
                  {employee.full_name}
                </Badge>
              ))}
            </div>
          </div>
        )}

        <div className="overflow-x-auto px-4 pb-4">
          <table className="w-full text-left text-sm">
            <thead className="bg-muted">
              <tr>
                <th className="px-3 py-2 font-medium text-muted-foreground">Employee</th>
                <th className="px-3 py-2 font-medium text-muted-foreground">Type</th>
                <th className="px-3 py-2 text-right font-medium text-muted-foreground">Gross</th>
                <th className="px-3 py-2 text-right font-medium text-muted-foreground">Deductions</th>
                <th className="px-3 py-2 text-right font-medium text-muted-foreground">Net</th>
                <th className="px-3 py-2 font-medium text-muted-foreground">Status</th>
                <th className="px-3 py-2 font-medium text-muted-foreground" />
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {run.payslips.map((payslip) => (
                <tr key={payslip.id}>
                  <td className="px-3 py-2">
                    <div className="flex flex-col">
                      <span className="font-medium text-foreground">{payslip.employee_name}</span>
                      <span className="text-xs text-muted-foreground">{payslip.employee_code}</span>
                    </div>
                  </td>
                  <td className="px-3 py-2 capitalize text-muted-foreground">{payslip.employee_type}</td>
                  <td className="px-3 py-2 text-right">{formatMoney(payslip.gross_amount)}</td>
                  <td className="px-3 py-2 text-right">{formatMoney(payslip.deductions)}</td>
                  <td className="px-3 py-2 text-right font-medium text-foreground">{formatMoney(payslip.net_amount)}</td>
                  <td className="px-3 py-2">
                    <Badge variant={PAYSLIP_STATUS_BADGE_VARIANT[payslip.status] ?? "muted"}>
                      {PAYSLIP_STATUS_LABELS[payslip.status]}
                    </Badge>
                  </td>
                  <td className="px-3 py-2 text-right">
                    {canManage && payslip.status === "pending" && (
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={markPaidMutation.isPending}
                        onClick={() => markPaidMutation.mutate(payslip.id)}
                      >
                        Mark paid
                      </Button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
