"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/shared/data-table";
import { loginErrorMessage } from "@/hooks/use-auth";
import { usePayrollRunsQuery } from "@/hooks/use-payroll";
import { MONTH_LABELS, PAYROLL_STATUS_LABELS, type PayrollStatus } from "@/lib/api/payroll";

const STATUS_BADGE_VARIANT: Record<string, "success" | "warning" | "muted"> = {
  paid: "success",
  processed: "warning",
  draft: "muted",
};

const STATUS_OPTIONS: PayrollStatus[] = ["draft", "processed", "paid"];

function formatMoney(amount: number): string {
  return amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function PayrollRunListTable({ runBasePath }: { runBasePath: string }) {
  const router = useRouter();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState<PayrollStatus | "all">("all");
  const [page, setPage] = useState(1);
  const limit = 20;

  const runsQuery = usePayrollRunsQuery({ status: status === "all" ? undefined : status, page, limit });
  const allItems = runsQuery.data?.items ?? [];
  const items = search
    ? allItems.filter((run) => run.generated_by_name.toLowerCase().includes(search.toLowerCase()))
    : allItems;

  const rows = items.map((run) => ({
    period: (
      <span className="font-medium text-foreground">
        {MONTH_LABELS[run.period_month - 1]} {run.period_year}
      </span>
    ),
    status: <Badge variant={STATUS_BADGE_VARIANT[run.status] ?? "muted"}>{PAYROLL_STATUS_LABELS[run.status]}</Badge>,
    payslips: String(run.payslip_count),
    total_net: formatMoney(run.total_net_amount),
    generated_by: run.generated_by_name,
  }));

  return (
    <DataTable
      title="Payroll runs"
      description="Generated payroll runs across all periods."
      columns={[
        { key: "period", label: "Period" },
        { key: "status", label: "Status" },
        { key: "payslips", label: "Payslips", align: "right" },
        { key: "total_net", label: "Total net", align: "right" },
        { key: "generated_by", label: "Generated by" },
      ]}
      rows={rows}
      isLoading={runsQuery.isLoading}
      isError={runsQuery.isError}
      errorMessage={runsQuery.error ? loginErrorMessage(runsQuery.error) : undefined}
      onRetry={() => runsQuery.refetch()}
      emptyMessage="No payroll runs generated yet."
      searchValue={search}
      onSearchChange={setSearch}
      searchPlaceholder="Search by generated-by name"
      page={page}
      limit={limit}
      total={runsQuery.data?.meta.total ?? 0}
      onPageChange={setPage}
      onRowClick={(index) => router.push(`${runBasePath}/${items[index].id}`)}
      toolbarActions={
        <Select value={status} onValueChange={(value) => setStatus(value as PayrollStatus | "all")}>
          <SelectTrigger className="w-[10rem]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            {STATUS_OPTIONS.map((s) => (
              <SelectItem key={s} value={s}>
                {PAYROLL_STATUS_LABELS[s]}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      }
    />
  );
}
